version: "3.8"

services:
  bot:
    container_name: bti_bot

    build: .

    restart: unless-stopped

    user: root

    volumes:
      - bti-bot-session-volume:/usr/src/app/auth_info_baileys

    environment:
      - API_BASE_URL=${API_BASE_URL}
      - API_SECRET_KEY=${API_SECRET_KEY}

volumes:
  bti-bot-session-volume:
    driver: local
