const foods = {
 proteins: [
  "Salmão selvagem",
  "Atum Ahi",
  "Bacalhau do Alasca",
  "Linguado",
  "Robalo",
  "Truta arco-íris",
  "Carne de caranguejo",
  "Lagosta",
  "Vieiras",
  "Mexilhões",
  "Ostras",
  "Camarão",
  "Vaca Wagyu",
  "Filé Mignon",
  "Costeletas de cordeiro",
  "Pato",
  "Faisão",
  "Codorna",
  "Peru orgânico",
  "Frango de capoeira",
  "Pato de Barbary",
  "Coelho",
  "Cordeiro lechal",
  "Búfalo",
  "Carne de alce",
  "Carne de veado",
  "Carne de avestruz",
  "Pato selvagem",
  "Codorna de montanha",
  "Cervo selvagem"
],
sideDishes: [
 "Risoto de cogumelos selvagens",
 "Purê de batata trufado",
 "Aspargos grelhados com molho hollandaise",
 "Legumes salteados na manteiga de ervas",
 "Batatas gratinadas com queijo Gruyère",
 "Salada de rúcula, pera e queijo gorgonzola",
 "Brócolis assados com alho e parmesão",
 "Cuscuz marroquino com frutas secas e castanhas",
 "Arroz selvagem com amêndoas",
 "Batata doce assada com molho de maple",
 "Purê de abóbora com noz-moscada",
 "Salada de quinoa com vegetais assados",
 "Cenouras glaceadas com mel e alecrim",
 "Purê de couve-flor com alho e queijo parmesão",
 "Espinafre salteado com pinhões e passas",
 "Salada de lentilha com tomate seco e queijo feta",
 "Couve de Bruxelas assadas com bacon",
 "Purê de mandioquinha com gengibre",
 "Salada de beterraba assada com queijo de cabra",
 "Abóbora assada com pimenta rosa",
 "Grão-de-bico crocante com especiarias",
 "Salada de cevada com abobrinha grelhada",
 "Champignons recheados com queijo de cabra",
 "Batatas doces assadas com páprica defumada",
 "Salada de lentilha com queijo de cabra e pêssego grelhado",
 "Couscous de couve-flor com ervas frescas",
 "Purê de batata-doce com marshmallow",
 "Salada de trigo sarraceno com legumes grelhados",
 "Purê de inhame com manteiga de ervas",
 "Salada de feijão branco com tomate cereja e manjericão"
],
sauces: [
 "Molho v1.0.0",
 "Molho v1.1.0",
 "Molho v1.2.0",
 "Molho v1.3.0",
 "Molho v1.4.0",
 "Molho v1.5.0",
 "Molho v1.6.0",
 "Molho v1.7.0",
 "Molho v1.8.0",
 "Molho v1.9.0",
 "Molho v2.0.0",
 "Molho v2.1.0",
 "Molho v2.2.0",
 "Molho v2.3.0",
 "Molho v2.4.0",
 "Molho v2.5.0",
 "Molho v2.6.0",
 "Molho v2.7.0",
 "Molho v2.8.0",
 "Molho v2.9.0",
 "Molho v3.0.0",
],

desserts: [
 "Crème brûlée",
 "Tiramisù",
 "Mousse de chocolate belga",
 "Pavlova com frutas frescas",
 "Macarons",
 "Sorvete de baunilha com coulis de frutas vermelhas",
 "Profiteroles com creme de confeiteiro e calda de chocolate",
 "Tarte Tatin",
 "Panna cotta com coulis de frutas",
 "Soufflé de chocolate",
 "Cheesecake de framboesa",
 "Crepes Suzette",
 "Torta de limão com merengue italiano",
 "Parfait de frutas frescas com creme Chantilly",
 "Baba au rhum",
 "Tarte au citron",
 "Éclair de chocolate",
 "Fondue de chocolate com frutas frescas",
 "Gâteau Saint-Honoré",
 "Creme de Papaya com Cassis",
 "Petit Gateau",
 "Clafoutis de cereja",
 "Banana Foster",
 "Charlotte de morango",
 "Bolo Red Velvet",
 "Sorvete de pistache com calda de framboesa",
 "Canelé bordelais",
 "Mil-folhas de creme de baunilha",
 "Torta de amêndoa",
 "Savarin"
]
};

module.exports = foods;