export const ia = {
  fullName: "Inteligência Artificial",
  chMin: 360,
  courses: [
    {
      cod: "IMD3002",
      name: "Aprendizado de Máquina Supervisionado",
      ch: 60,
      optative: false,
    },
    {
      cod: "IMD1114",
      name: "Aprendizado Profundo",
      ch: 60,
      optative: false,
    },
    {
      cod: "IMD3003",
      name: "Aprendizado de Máquina Não-Supervisionado",
      ch: 30,
      optative: true,
    },
    {
      cod: "IMD1112",
      name: "Ética e Dados",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD1113",
      name: "Probabilidade e Inferência",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD1103",
      name: "Aprendizado por Reforço",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD1107",
      name: "Processamento de Linguagem Natural",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD1108",
      name: "Visão Computacional",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD1115",
      name: "Processamento Digital de Imagem",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD1116",
      name: "Computação de Alto Desempenho",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD1117",
      name: "Álgebra Computacional",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD0607",
      name: "Modelagem e Simulação Computacional",
      ch: 60,
      optative: true,
    },
    {
      cod: "DIM0126",
      name: "Inteligência Artificial para Jogos I",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD0814",
      name: "Inteligência Artificial para Jogos II",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD0511",
      name: "Inteligência Artificial Aplicada a Educação",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD1152",
      name: "Coleta e Raspagem de Dados",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD3004",
      name: "IA Generativa",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD3005",
      name: "MLOps",
      ch: 60,
      optative: true,
    },
    {
      cod: "DIM0613",
      name: "Inteligência Artificial",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD1133",
      name: "Aprendizado de Máquina Aplicado ao Mercado Financeiro",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD1309",
      name: "Transformação Digital",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD3011",
      name: "Datacentric AI",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD1120",
      name: "Tópicos Especiais em Inteligência Artificial “A”",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD1121",
      name: "Tópicos Especiais em Inteligência Artificial “B”",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD1122",
      name: "Tópicos Especiais em Inteligência Artificial “C”",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD1123",
      name: "Tópicos Especiais em Inteligência Artificial “D”",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD1124",
      name: "Tópicos Especiais em Inteligência Artificial “E”",
      ch: 30,
      optative: true,
    },
    {
      cod: "IMD1125",
      name: "Tópicos Especiais em Inteligência Artificial “F”",
      ch: 30,
      optative: true,
    },
  ],
};
