export const iot = {
  fullName: "Internet das Coisas",
  chMin: 300,
  courses: [
    {
      cod: "IMD0902",
      name: "Introdução a Internet das Coisas",
      ch: 60,
      optative: false,
    },
    {
      cod: "IMD0904",
      name: "Plataformas de Hardware para Internet das Coisas",
      ch: 60,
      optative: false,
    },
    {
      cod: "IMD0907",
      name: "Tecnologias de Comunicação para Internet das Coisas",
      ch: 60,
      optative: false,
    },
    {
      cod: "IMD1151",
      name: "Ciência de Dados",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD0911",
      name: "Aplicações em Internet das Coisas",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD0912",
      name: "Metodologia de Projeto de IoT",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD0910",
      name: "Segurança e Privacidade em Internet das Coisas",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD0908",
      name: "Computação Elástica para Internet das Coisas",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD0913",
      name: "Blockchain e Aplicações Descentralizadas",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD0296",
      name: "Projeto de IoT",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD0297",
      name: "CCNA1 - Introduction to Networks",
      ch: 30,
      optative: true,
    },
    {
      cod: "IMD0298",
      name: "CCNA2 - Switching, Routing, and Wireless Essentials",
      ch: 30,
      optative: true,
    },
    {
      cod: "IMD0299",
      name: "CCNA3 - Enterprise Networking, Security, and Automation",
      ch: 30,
      optative: true,
    },
    {
      cod: "IMD0289",
      name: "Fundamentos de Eletrônica para IoT",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD3002",
      name: "Aprendizado de Máquina Supervisionado",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD3003",
      name: "Aprendizado de Máquina Não-Supervisionado",
      ch: 30,
      optative: true,
    },
    {
      cod: "IMD0290",
      name: "Tópicos Especiais em Internet das Coisas “A”",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD0291",
      name: "Tópicos Especiais em Internet das Coisas “B”",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD0292",
      name: "Tópicos Especiais em Internet das Coisas “C”",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD0293",
      name: "Tópicos Especiais em Internet das Coisas “D”",
      ch: 60,
      optative: true,
    },
    {
      cod: "IMD0294",
      name: "Tópicos Especiais em Internet das Coisas “E”",
      ch: 30,
      optative: true,
    },
    {
      cod: "IMD0295",
      name: "Tópicos Especiais em Internet das Coisas “F”",
      ch: 30,
      optative: true,
    },
  ],
};
